config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"

resources :favourites, only: [:index]

  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :index]
    resources :favourites, only: [:new, :create, :destroy]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy

  validates :brand, :model, :year, :fuel, presence: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car

  validates :car_id, uniqueness: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars, dependent: :destroy

  validates :nickname, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :comment, presence: true, length: { minimum: 5, maximum: 500 }
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @favourite = Favourite.new
    @review = Review.new
    @reviews = @car.reviews
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all
  end

  def create
    @car = Car.find(params[:car_id])
    @favourite = Favourite.new(car: @car)
      if @favourite.save
        redirect_to @car, notice: "#{@car.brand} has been added to your garage!"
      else
        redirect_to @car, alert: "There was an error adding this car to your garage."
      end
  end

  def destroy
    @favourite = Favourite.find(params[:id]) # Locate the specific favourite
    @favourite.destroy
    redirect_to favourites_path, notice: "Car removed from garage."
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_car

  def index
    @reviews = @car.reviews
  end

  def new
    @review = @car.reviews.new
  end

  def create
    @review = @car.reviews.new(review_params)
    if @review.save
      redirect_to car_path(@car), notice: 'Review created successfully!'
    else
      render :new
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Converts a numeric rating into emoji stars (out of 5)
  # @param rating [Float, Integer] The rating to convert (e.g., 3.5, 4, etc.)
  # @return [String] A string of emoji stars
  def rating_to_stars(rating)
    # Clamp the rating between 0 and 5 to handle edge cases
    rating = [[rating, 0].max, 5].min

    # Calculate full stars, half stars, and empty stars
    full_stars = rating.floor

    # Build the emoji star string
    "⭐" * full_stars
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/cars/index.html.erb
<% @cars.each do |car| %>
  <%= link_to car_path(car) do %>
    <div class="card-car">
       <div class="card-car-infos">
        <h2><%= "#{car.brand}" %></h2>
        <h3><%= "#{car.model} | (#{car.year})" %></h3>
      </div>
      <div class="card-car-image">
        <%= image_tag(car.image_url, alt: "#{car.brand} #{car.model}") if car.image_url.present? %>
      </div>
      <div class="card-car-infos">
      <h3>Comment</h3> <i class="fa-solid fa-comment"></i>
      </div>
    </div>
  <% end %>
<% end %>

app/views/cars/show.html.erb
  <div class="card-car">
     <div class="card-car-image">
        <%= image_tag(@car.image_url, alt: "#{@car.brand} #{@car.model}") if @car.image_url.present? %>
      </div>
    <div class="card-car-infos">
      <h1><%= "#{@car.brand}" %>
      <p><%= "#{@car.model} | (#{@car.year})" %>
      <%= simple_form_for [@car, @favourite] do |f| %>
      <%= f.submit "Add to garage", class: "btn btn-success" %>
      <% end %>
    </div>
     <div class="form">
        <h3>Leave a comment</h3>
          <%= simple_form_for [@car, @review] do |f| %>
            <%= f.input :comment %>
            <%= f.input :rating, input_html: { type: 'range', min: 0, max: 5, step: 1 }, label: "Rating (0 to 5)" %>
            <%= f.submit "Submit", class: "btn btn-success" %>
          <% end %>
      <h3>Comments</h3>
        <ul>
          <% @reviews.each do |review| %>
          <li>"<%= review.comment %>" | <%= rating_to_stars(review.rating) %></li>
            <% end %>
        </ul>
    </div>
  </div>



<%# <%= link_to "Leave a review", new_car_review_path(@car), class: "btn btn-primary" %>

app/views/favourites/index.html.erb
<h1>MY GARAGE</h1>

<ul>
  <% @favourites.each do |favourite| %>
    <li>
      <div class="card-favourite">
        <%= image_tag(favourite.car.image_url) %>
          <div class="card-favourite-infos">
              <%= favourite.car.brand %> - <%= favourite.car.model %>
              <%= favourite.car.year %> | <%= favourite.car.fuel %>
              <%= link_to car_favourite_path(favourite.car, favourite),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: "btn btn-delete" do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
        </div>
      </div>
   </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <% unless action_name == "home" %>
       <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class ="home-center">
  <%= link_to cars_path do %>
    <%= image_tag "awesome-garage-logo-2.svg", alt: "Awesome Garage Logo", class: "home-logo" %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="form">
  <div class="card-form">
    <h1>Leave a review for <%= @car.brand %></h1>
    <%= simple_form_for [@car, @review] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating, input_html: { type: 'range', min: 0, max: 5, step: 1 }, label: "Rating (0 to 5)" %>
      <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav">
  <%= link_to root_path do %>
    <%= image_tag "awesome-garage-logo.svg", alt: "Awesome Garage Logo", class: "navbar-logo" %>
  <% end %>
  <div class="nav-right">
    <%= link_to 'HOME', root_path %>
    <%= link_to 'MY GARAGE', favourites_path %>
  </div>
</div>